@echo off
CLS
ECHO Generate .XSD file from source DLL files

ECHO.
ECHO Step (1/6) - Preparations

REM Prepare folders
set sourceDLL=%cd%\dll
set targetXSD=%cd%\xsd_autogenerated
ECHO DLL folder (source) = %sourceDLL%
ECHO Autogenerated XSD folder (target) = %targetXSD%

REM Iterate files in DLL subdir and put in string (since XSD.exe cannot handle * to process multiple files at once)
setlocal enabledelayedexpansion
set dll_files=
for /r %sourceDLL% %%f in (*.dll) do (
    set dll_files=!dll_files! "%%~dpf%%~nxf"
)
echo DLL files found = %dll_files%

REM Prepare XSD filename
for %%I in (.) do set CurrDirName=%%~nxI
set targetXSDFileName=%CurrDirName%.xsd
ECHO Subfoldername = %CurrDirName%
ECHO Target XSD filename = %targetXSDFileName%

ECHO.
ECHO Step (2/6) - Check XSD dir and remove old files (if any)
if not exist "%targetXSD%" mkdir "%targetXSD%"
del %targetXSD%\*.xsd

ECHO.
ECHO Step (3/6) - Generate CS file from XSD source files
xsd.exe %dll_files%

ECHO.
ECHO Step (4/6). Rename generated XSD file
ren "*.xsd" "%targetXSDFileName%"

ECHO.
ECHO Step (5/6) - Move generated XSD file to XSD subfolder
move "*.xsd" "%targetXSD%"

ECHO.
ECHO Step (6/6) - Generation completed

ECHO.
PAUSE